# NOTE
# When changing anything under directory /pkg/ locally
# you can build & push this image and then base off the images inside /cmd/ on it
# in order for OM components to pick up your changes

FROM golang:1.11
RUN go get -d -v github.com/ihrankouski/open-match
COPY pkg /go/src/github.com/ihrankouski/open-match/pkg
