starter:
  profile: profiles/__empty__.json
  minPlayers: 20
  maxWaitSeconds: 3600
profiles:
- profiles/testprofile.json
- profiles/something.json
agones:
  namespace: default
  fleetName: udp-server
  generateName: udp-server-
